services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
  softallainceapi:
    build: .
    environment:
      - MONGO_URL=mongodb://mongo:27017/softallaince
    depends_on:
      - mongo